id: A9AA2865B
title: Prayer to the Lineage of the Great Chetsün’s Profound Essence of Vimala
type: translation
pechas:
- IA21A103D
- IA1429FA6
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:09.753143
  last_modified_at: 2023-01-04 12:01:09.753147
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  IA21A103D/5B55: 88C3
  IA1429FA6/074B: 88C3
